id: CVE-2017-7501

info:
  name: Jboss反序列化漏洞 (CVE-2017-7501)
  author: SleepingBag945
  severity: critical
  description: |
    JBoss JMXInvokerServlet 反序列化漏洞 (CVE-2017-7501)
    JBoss在/invoker/JMXInvokerServlet 请求中读取了用户传入的对象，存在反序列化漏洞。
  tags: CVE,jboss

http:
  - raw:
      - |
        GET /invoker/JMXInvokerServlet  HTTP/1.1
        Host: {{Hostname}}


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"jboss") && contains(body_1,"java")'
        condition: and

# https://github.com/ggyao/jbossscan, https://github.com/joaomatosf/JavaDeserH2HC