id: CVE-2017-7504

info:
  name: JBoss 4.x JBossMQ JMS 反序列化漏洞 (CVE-2017-7504)
  author: SleepingBag945
  severity: critical
  description: |
    JBoss 4.x JBossMQ JMS 反序列化漏洞
  tags: CVE,jboss

http:
  - raw:
      - |
        GET /jbossmq-httpil/HTTPServerILServlet  HTTP/1.1
        Host: {{Hostname}}


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"This is the JBossMQ HTTP-IL")'
        condition: and

# https://github.com/vulhub/vulhub/tree/master/jboss/CVE-2017-7504
# https://github.com/ggyao/jbossscan, https://github.com/joaomatosf/JavaDeserH2HC
# http://wiki.peiqi.tech/wiki/webserver/JBoss/JBoss%204.x%20JBossMQ%20JMS%20%E5%8F%8D%E5%BA%8F%E5%88%97%E5%8C%96%E6%BC%8F%E6%B4%9E%20CVE-2017-7504.html